config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

  devise_scope :user do
    authenticated :user do
      root 'users#current_user_home', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :users do
    member do
      get 'movies'
      get 'shows'
      get 'friends'
      get 'dashboard'
    end
  end
  resources :recommendations
  get '/media/search', to: 'media#search'
  resources :media
  resources :tags
  resources :shows
  resources :movies
  resources :likes
  resources :friendships

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
	before_action :find_movie, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!

	def index
		@all_tags = Tag.all
  	@percents = {}

		@tags = {}
		@all_tags.each do |tag|
			movies = tag.movies.take(10)
			if !movies.empty?
				@tags[tag] = movies
				movies.each {|movie| @percents[movie.medium_id] = movie.percents}
			end
		end

		@most_watched_movies = Medium.where(media_type: "Movie").order(watched_count: :desc).limit(24).map {|movie| movie = movie.find_associated_media}
    @most_liked_movies = Medium.where(media_type: "Movie").order(liked_count: :desc).limit(24).map {|movie| movie = movie.find_associated_media}
    @most_recommended_movies = Medium.where(media_type: "Movie").order(recommended_count: :desc).limit(24).map {|movie| movie = movie.find_associated_media}

  	@current_user_likes = current_user.movie_likes

  	@most_watched_movies.each {|movie| @percents[movie.medium_id] = movie.percents }
  	@most_liked_movies.each {|movie| @percents[movie.medium_id] = movie.percents }
  	@most_recommended_movies.each {|movie| @percents[movie.medium_id] = movie.percents }

	end

	def show
		med = Movie.find(params[:id]).medium.id
  	@current_user_likes = current_user.movie_likes
  	@friends_like = friends_like(med, 1)
  	@friends_seen = friends_like(med, 0)
  	@friends_dislike = friends_like(med, -1)

  	@percents = @movie.percents

	end

	def create

	end

	private

	def friends_like(id, value)
		friends = []
		current_user.friends.each do |friend|
			friends << friend if friend.movie_likes[id] == value
		end
		friends
	end

	def find_movie
		@movie = Movie.find(params[:id])
	end

	def movie_params
		params.require(:movie).permit(:title, :year, :rated, :released, :runtime, :genre, :director, :writer, :actors, :plot, :poster, :media_type, :imdb_id, :points)
	end

end

app/views/movies/index.html.erb
<h1 class="text_center">All Movies</h1>

<div class="media_index_wrapper">

	<h2 class="media_header">Most Viewed Movies</h2>
	<div class="media_index_tag_wrapper">
		<% @most_watched_movies.each do |movie| %>
			<div class="media_index_element_wrapper">
				Views: <%= movie.medium.watched_count %>
				<%= render partial: 'layouts/media_movie_layout', locals: { current_user_likes: @current_user_likes, placeholder: movie, current_user: current_user, percent: @percents[movie.medium_id]} %>
			</div>
		<% end %>
	</div>

	<h2 class="media_header">Most Liked Movies</h2>
	<div class="media_index_tag_wrapper">
		<% @most_liked_movies.each do |movie| %>
			<div class="media_index_element_wrapper">
				Likes: <%= movie.medium.liked_count %>
				<br>
				<%= render partial: 'layouts/media_movie_layout', locals: { current_user_likes: @current_user_likes, placeholder: movie, current_user: current_user, percent: @percents[movie.medium_id]} %>
			</div>
		<% end %>
	</div>

	<h2 class="media_header">Most Recommended Movies</h2>
	<div class="media_index_tag_wrapper">
		<% @most_recommended_movies.each do |movie| %>
			<div class="media_index_element_wrapper">
			Recommends: <%= movie.medium.recommended_count %>
			<br>
			<%= render partial: 'layouts/media_movie_layout', locals: { current_user_likes: @current_user_likes, placeholder: movie, current_user: current_user, percent: @percents[movie.medium_id]} %>
		</div>
		<% end %>
	</div>
	
	<% @tags.each_key do |tag| %>
		<h2 class="media_header"><%= link_to tag.name, tag %></h3>
		<div class="media_index_tag_wrapper">
			<% @tags[tag].each do |movie| %>
				<%= render partial: 'layouts/media_movie_layout', locals: { current_user_likes: @current_user_likes, placeholder: movie, current_user: current_user, percent: @percents[movie.medium_id]} %>
			<% end %>
		</div>
	<% end %>
</div>

app/views/movies/show.html.erb
<div class="media_show_wrapper">
	<div class="media_movie_title">
		<%= @movie.title %>
	</div>
	<div class="info_one">
		<%= render partial: 'layouts/icons', locals: { current_user_likes: @current_user_likes, placeholder: @movie, current_user: current_user } %>
		<%= @movie.year %>  
		(<%= @movie.rated %>)  
		<%= @movie.runtime %>		
	</div>
	<br>
	<div class="media_plot">
		<%= @movie.plot %>
	</div>
	<br>
	Tags: <% @movie.medium.tags.each do |tag| %>
		<%= link_to tag.name,  tag_path(tag) %>
	<% end %>
	<br>
	Director: <%= @movie.director %>
	<br>
	Writer: <%= @movie.writer %>
	<br>
	Starring: <%= @movie.actors %>
	<br>
	<div class="movie_poster">
		<div class="bar_mortice mortice_tiny" style="width: 266px">
		  <div class="progress progress_tiny green" style="width: <%= @percents[0] %>%;"></div>
		  <div class="progress progress_tiny yellow" style="width: <%= @percents[1] %>%;"></div>
		  <div class="progress progress_tiny red" style="width: <%= @percents[2] %>%;"></div>
		</div>
		<img class="full_poster" src="<%= @movie.poster %>">
	</div>
</div>
<div class="media_show_info">
	Number of people who have recommended this Movie: <%= @movie.medium.recommended_count %>
	<br>
	You have recommended this Movie to:
	<br>
	<% @movie.medium.recommended_to(current_user.id).each do |person| %>
		<%= link_to person.name, user_path(person) %>
		<br>
	<% end %>
	<br>
	Have recommended this Movie to you:
	<br>
	<% @movie.medium.recommended_by(current_user.id).each do |person| %>
		<%= link_to person.name, user_path(person) %>
		<br>
	<% end %>
	<br>
	Friends who like this Movie:
	<br>
	<% @friends_like.each do |person| %>
		<%= link_to person.name, user_path(person) %>
		<br>
	<% end %>
	<br>
		Friends who have seen this Movie:
	<br>
	<% @friends_seen.each do |person| %>
		<%= link_to person.name, user_path(person) %>
		<br>
	<% end %>
	<br>
	Friends who dislike this Movie:
	<br>
		<% @friends_dislike.each do |person| %>
		<%= link_to person.name, user_path(person) %>
		<br>
	<% end %>
	<br>
</div>