config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

  devise_scope :user do
    authenticated :user do
      root 'users#current_user_home', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :users do
    member do
      get 'movies'
      get 'shows'
      get 'friends'
      get 'dashboard'
    end
  end
  resources :recommendations
  get '/media/search', to: 'media#search'
  resources :media
  resources :tags
  resources :shows
  resources :movies
  resources :likes
  resources :friendships

end

app/views/old/dashboard.html.erb
<%= render partial: 'layouts/endorsesaurus_enclosure', locals: { current_user: current_user, user: @user } %>
<%= render partial: 'layouts/secondary_nav_bar', locals: { user: @user } %>

<div class="dashboard_container">
  <div class="dashboard_recents_list">
  <h3 class="text_center">Your friend's recent activity:</h3>
    <% @friends_recents.each do |note| %>
      <% case note.note_type %>
        <% when "RecNote" %>
          <div class="event_wrapper">
            <%= render partial: 'layouts/event_rec_note', locals: { note: note, user: @user } %>
            <%= render partial: 'layouts/poster_icon_large', locals: { media: note.media } %>
          </div>
          <br>

        <% when "WatchedRecNote" %>
          <div class="event_wrapper">
            <%= render partial: 'layouts/event_watched_rec_note', locals: { note: note, user: @user } %>
            <%= render partial: 'layouts/poster_icon_large', locals: { media: note.media } %>
          </div>
          <br>

        <% when "WatchedNote" %>
          <div class="event_wrapper">
            <%= render partial: 'layouts/event_watched_note', locals: { note: note, user: @user } %>
            <%= render partial: 'layouts/poster_icon_large', locals: { media: note.media } %>
          </div>
          <br>

      <% end %>
    <% end %>
  </div>
</div>

app/views/old/friends.html.erb
<%= render partial: 'layouts/endorsesaurus_enclosure', locals: { current_user: current_user, user: @user } %>
<%= render partial: 'layouts/secondary_nav_bar', locals: { user: @user } %>

<div class="left_col">
</div>

<div>
  <h3 class="text_center"><%= @user.name %>'s Friends</h3>
  <ul class="text_center">
    <% @user.friends.each do |friend| %>
      <div class="friend_icon_wrapper">
        <%= link_to image_tag('profile.jpg'), friend, class: "photo_icon"%>
        <br>
        <%= link_to friend.name, friend, class: "text_center" %> 
        <br>
        <% if current_user == @user %>
          <%= link_to "(Delete)", friendship_path(:id => friend), :method => :delete, class: "text_center" %>
        <% end %>
        <br>
        <br>
      </div>
    <% end %>
  </ul>

  <% if current_user == @user %>
      <h3 class="text_center">Friend Requests</h3>
      <ul class="text_center">
        <% @user.requested_friendships.each do |request| %>
          <div class="friend_icon_wrapper">
            <%= link_to image_tag('profile.jpg'), request, class: "photo_icon"%>
            <br>
            <%= link_to request.name, request, class: "text_center" %>
            <br>
            <%= link_to "(Accept)", friendship_path(:id => request), :method => "put", class: "text_center" %>
            <br>
            <%= link_to "(Decline)", friendship_path(:id => request), :method => :delete, class: "text_center" %>
            <br>
            <br>
          </div>
        <% end %>
      </ul>
  <% end %>

   <% if current_user == @user %>
    <h3 class="text_center">Pending Requests</h3>
    <ul class="text_center">
      <% @user.pending_friends.each do |request| %>
        <div class="friend_icon_wrapper">
          <%= link_to image_tag('profile.jpg'), request, class: "photo_icon"%>
          <br>
          <%= link_to request.name, request, class: "text_center" %> 
          <br>
          <br>
        </div>
      <% end %>
    </ul>
  <% end %>
</div>

app/views/old/header.html.erb
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<header class ="navbar-wrapper">
  <div class="site-name">
    <%= image_tag('derpy_dinosaur.png', size: "30") %>
    Endorsesaurus: Tip the Scales
  </div>
  <div class ="navbar-class">
    <% if current_user %>
      <ul class="navbar-left navbar">
        <li class="nav_element"><%= link_to "Movies", movies_path %></li>
        <li class="nav_element"><%= link_to "Shows", shows_path %></li>
        <li class="nav_element"><%= link_to "Tags", tags_path %></li>
      </ul>
      <ul class="search_bar navbar">
        <li class="search">
          <%= form_tag('/media/search', method: :get) do |f| %>
            <%= text_field_tag :title, params[:title] %>
            <%= select_tag "media", options_for_select(["Movies", "Shows"], "Shows")%>
            <%= submit_tag "Search" %>
          <% end %>
        </li>
      </ul>
      <ul class="navbar-right navbar">
        (<%= current_user.points %>)
        <%= link_to image_tag('profile.jpg'), user_path(current_user), class: "photo_icon_small" %>
        <li class="nav_element"><%= link_to current_user.name, dashboard_user_path(current_user) %>
          <ul>
            <li class="dropdown_element"><%= link_to "Profile", current_user %></li>
            <li class="dropdown_element"><%= link_to "Friends", friends_user_path(current_user) %></li>
            <li class="dropdown_element"><%= link_to "Movies", movies_user_path(current_user) %></li>
            <li class="dropdown_element"><%= link_to "Shows", shows_user_path(current_user) %></li>
            <li class="dropdown_element"><%= render 'devise/menu/registration_items' %></li>
            <li class="dropdown_element"><%= render 'devise/menu/login_items' %></li>
          </ul>
        </li>
      </ul>
    <% end %>
  </div>
</header>

app/views/old/movies.html.erb
<%= render partial: 'layouts/endorsesaurus_enclosure', locals: { current_user: current_user, user: @user } %>
<%= render partial: 'layouts/secondary_nav_bar', locals: { user: @user } %>

<div class="recommendations_container">
  <h3 class="text_center">Movie Recommendations:</h3>
  <div class="recommendation_wrapper">
    <% if @movie_recs && !@movie_recs.empty? %>
      <% @movie_recs.each do |rec| %>
        <%= render partial: 'layouts/recommended_movie_layout', locals: { user: @user, current_user_likes: @current_user_likes, rec: rec, current_user: current_user, percents: @percents[rec.info.medium_id]} %>
        <br>
      <% end %>
    <% else %>
      <p>No Recommendations to show!</p>
    <% end %>
  </div>
</div>


<div class="likes_container">
  <h3>
  <span class="likes_button">Likes</span> 
  <span class="seen_button">Seen</span> 
  <span class="dislikes_button">Dislikes</span>
  </h3>
  <div class="watched_wrapper">

    <div class="likes_wrapper">
      <% if @likes && !@likes.empty? %>
        <% @likes.each do |like| %>
          <%= render partial: 'layouts/movie_layout', locals: { user: @user, user_likes: @user_likes, current_user_likes: @current_user_likes, placeholder: like, current_user: current_user, percents: @percents[like.medium_id]} %> 
          <br>
        <% end %>
      <% else %>
        <p>No likes to show!</p>
      <% end %>
    </div>

    <div class="seen_wrapper">
      <% if @seens && !@seens.empty? %>
        <% @seens.each do |seen| %>
          <%= render partial: 'layouts/movie_layout', locals: { user: @user, user_likes: @user_likes, current_user_likes: @current_user_likes, placeholder: seen, current_user: current_user, percents: @percents[seen.medium_id]} %> 
          <br>
        <% end %>
      <% else %>
        <p>No seens to show!</p>
      <% end %>
    </div>

    <div class="dislikes_wrapper">
      <% if @dislikes && !@dislikes.empty? %>
        <% @dislikes.each do |dislike| %>
          <%= render partial: 'layouts/movie_layout', locals: { user: @user, user_likes: @user_likes, current_user_likes: @current_user_likes, placeholder: dislike, current_user: current_user, percents: @percents[dislike.medium_id]} %> 
          <br>
        <% end %>
      <% else %>
        <p>No dislikes to show!</p>
      <% end %>
    </div>
  </div>
</div>